### ISSUE TITLE
doc: clearly document that different BLAS implementations have different behaviour

### ISSUE THREAD

**Issue by kortschak** [gonum/blas#118]
Moving from gonum/matrix#109.

We should also point out that we test against OpenBLAS in the cgo implementation.

**Comment by jonlawlor** [comment]
I think the gonum/blas lib should provide consistent behavior regardless of blas provider.  The easiest thing to do is just use the go implementation when the library provides inconsistent results.

**Comment by kortschak** [comment]
How do we know that the implementation chosen by the client is inconsistent with the reference and how do we know that that behaviour was not the behaviour they depend on?

**Comment by jonlawlor** [comment]
We could cover the ones we know about - all off them except OpenBLAS have one or two differences.  Clients should be depending on the *gonum/blas* implementation, not the particulars of ATLAS / Accelerate / OpenBLAS / whatever.  It would be quite a benefit.

**Comment by kortschak** [comment]
I really don't think we should do this.
