### ISSUE TITLE
.travis/check-generate.sh and go 1.3

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/blas#164]
`.travis/check-generate.sh` calls `go generate` but it is not supported by go 1.3 which still is in the build matrix. One option is to drop 1.3 (perhaps after 1.6 is out) or remove the script (and do the check in a git hook before pushing, for example).

**Comment by kortschak** [comment]
I want to drop 1.3 after 1.6 is out across the board, I just haven't gone through the issues. There are various TODOs to do with that.
