### ISSUE TITLE
issue setting up the CGO_LDFLAGS in windows 10

### ISSUE THREAD

**Issue by tensor-programming** [gonum/blas#205]
Not entirely sure how to setup the CGO_LDFLAGS environment var in windows.  Currently, i just made a new environment var named: CGO_LDFLAGS with the c:/path/to/openblas/bin as the source.  The way you have it structured however in the read me with the capital L preceding the path, is there some significance that i am missing?  (Its been a long time since I've worked with C and I never worked with it on windows.) 

Sorry if this is a stupid question.  Just can't seem to find a straight forward answer anywhere. 

Just FYI, im getting back an error that says the compile can't find -lopenblas.  Seems like i've entered the flag incorrectly. 

Heres my current CGO_LDFLAGS var: -L\C:\OpenBLAS -lopenblas

**Comment by vladimir-ch** [comment]
Closing because this repository is no longer maintained. Development has moved to https://github.com/gonum/gonum.
