### ISSUE TITLE
unable to install cgo as /usr/bin/ld cannpt find -openblas

### ISSUE THREAD

**Issue by aspk** [gonum/blas#206]
`CGO_LDFLAGS="-L/home/OpenBlas/lib -lopenblas" go install github.com/gonum/blas/cgo

output 

# github.com/gonum/blas/cgo
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status`

OS : Ubuntu 16.04

**Comment by Konstantin8105** [comment]
Please clarify - Are you install OpenBlas in according to https://github.com/gonum/blas/blob/master/README.md .

**Comment by vladimir-ch** [comment]
Closing because this repository is no longer maintained. Development has moved to https://github.com/gonum/gonum.
