### ISSUE TITLE
blas: Rewrite genBlas.pl in Go

### ISSUE THREAD

**Issue by kortschak** [gonum/blas#81]
I propose to rewrite genBlas.pl in Go.

This allows blas.h and blas.go to be generated and also provides the possibility to add doc comments to the methods (these would come from the doc comments in goblas when they are completed).

**Comment by fhs** [comment]
+1

Also, the documentation is very inconsistent on math notation. Sometimes it uses x' to mean transpose of x, and other times x**T or x^T. Constants are either spelled out like "alpha" or the corresponding unicode α. Assignment is either ":=" or "=". There needs to be some kind of standard for all gonum projects.

**Comment by kortschak** [comment]
That is an informal TODO for @btracey.

**Comment by jonlawlor** [comment]
Go generate requires 1.4, but users shouldn't need to call it or genBlas.pl, so I think this is a good idea.

**Comment by btracey** [comment]
Just a thought, this basically needs all of the relevant information, so this could be used to autogenerate benchmark code as well instead of the code that's there.

**Comment by vladimir-ch** [comment]
Done in #186
